/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 4
        max_iteration: 7
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./map.pcd"

        common:
            lid_topic:  "/zvlidar_points_xyzirt"
            imu_topic:  "/zvlidar_imu_msg"         
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 5
            scan_line: 192            # 96/192线
            scan_rate: 10
            timestamp_unit: 2
            blind: 0.3

        mapping:
            acc_cov: 0.3             # 
            gyr_cov: 0.01
            b_acc_cov: 0.01
            b_gyr_cov: 0.01
            fov_degree: 240.0
            det_range: 70.0
            extrinsic_est_en: false

            # 一径NZ 外参
            # extrinsic_T: [ -0.0026, -0.06545, 0.0161 ]
            # extrinsic_R: [ -1.,  0.,  0.,
            #                0.,  0., -1.,
            #                0., -1.,  0.]

            extrinsic_T: [ -0.0026, -0.06545, 0.0161 ]
            extrinsic_R: [ 1.,  0.,  0.,
                           0.,  1., 0.,
                           0., 0.,  1.]


        publish:
            path_en: true
            scan_publish_en: true
            dense_publish_en: false
            scan_bodyframe_pub_en: true

        pcd_save:
            pcd_save_en: true
            interval: -1
